AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Lambda Version Cleaner
Resources:
  lambdaCleaner:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime python3.7
      CodeUri: .
      Description: A Lambda Version Cleaner
      MemorySize: 128
      Timeout: 60
      Policies:
        - LambdaFullAccessPolicy:
